use [Synaps_IDMS]

/****** Object:  Table [dbo].[IDMS_Type]    Script Date: 01/25/2012 10:40:39 ******/
SET IDENTITY_INSERT [dbo].[IDMS_Type] ON
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (1, N'Home Address', NULL, N'ADDRESSTYPE', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (2, N'Billing Address', NULL, N'ADDRESSTYPE', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (3, N'Home Phone', NULL, N'PHONENUMBER', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (4, N'Work Phone', NULL, N'PHONENUMBER', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (5, N'Cell Phone', NULL, N'PHONENUMBER', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (6, N'Other Phone', NULL, N'PHONENUMBER', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate])
 VALUES (7, N'Park Guest', NULL, N'GUESTTYPE', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (8, N'Simulator Guest', NULL, N'GUESTTYPE', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (9, N'Test Guest', NULL, N'GUESTTYPE', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (10, N'gxp-link-id', NULL, N'SOURCESYSTEM', N'IDMS',GETUTCDATE(), N'IDMS',GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (11, N'Birthday', NULL, N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (12, N'Anniversary', NULL, N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (16, N'IDMS', NULL, N'SOURCESYSTEM', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (17, N'DME', NULL, N'SOURCESYSTEM', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (18, N'XBMS', NULL, N'SOURCESYSTEM', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (19, N'xid', NULL, N'SOURCESYSTEM', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (20, N'GuestEnteredScheduleItem', NULL, N'SCHEDULEITEM', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (21, N'NonBookableScheduleItem', NULL, N'SCHEDULEITEM', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (22, N'xband', NULL, N'SOURCESYSTEM', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (23, N'guest party', NULL, N'PARTYTYPE', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (26, N'Engagement', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (27, N'Graduation', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (28, N'Honeymoon', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (29, N'Personal Triumph', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (30, N'Reunion', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (31, N'Wedding', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (32, N'Other', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
INSERT [dbo].[IDMS_Type] ([IDMSTypeId], [IDMSTypeName], [IDMSTypeValue], [IDMSkey], [createdBy], [createdDate], [updatedBy], [updatedDate]) 
VALUES (33, N'First Visit', N'', N'CELEBRATION', N'IDMS', GETUTCDATE(), N'IDMS', GETUTCDATE())
SET IDENTITY_INSERT [dbo].[IDMS_Type] OFF
