#!/bin/sh

PROJECT_HOME=/usr/share/xbrc

if [ `id -u` -ne 0 ]; then
	echo "You need root privileges to run this script"
	exit 1
fi

CLASSPATH=$(echo "$PROJECT_HOME/lib"/*.jar | tr ' ' ':')
MAIN_CLASS=xbrmsregression.HealthItemsLoadTest

# run it
java -cp $CLASSPATH -Dlog4j.configuration=file:/usr/share/xbrc/xbrmsloadlog4j.xml $MAIN_CLASS $@
