CREATE TABLE [gxp].[XiPageGUIDs] (
    [XiGUIDId] INT           NOT NULL,
    [GUID]     NVARCHAR (40) NOT NULL,
    [Revision] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([XiGUIDId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

