#
# Common definitions and checks for scripts that manipulate and generate opkg
# repositories from the reader builds.
#
# * Checks that OEBASE is set
# * Checks that the opkg-make-idex command exits and adds the natively built 
#   tools directory to the PATH
# * Checks for the existance of the package directory generated by the builds
#   and sets the SOURCE_DIR variable to it's pathname
#

if [ -z $OEBASE ]; then
    echo "Error: OEBASE is undefined, run 'make setenv; source setenv' in the base directory to set it."
    exit 1
fi

# This file is needed to generate the opkg index - assumes we're building on a
# 64-bit linux machine.
if [ ! -f $OEBASE/arago-tmp/sysroots/x86_64-linux/usr/bin/opkg-make-index ]; then
    echo "Error: couldn't locate the native opkg-utils. Did you run a build yet?"
    exit 1
fi
export PATH=$PATH:$OEBASE/arago-tmp/sysroots/x86_64-linux/usr/bin

SOURCE_DIR=$OEBASE/arago-tmp/deploy/glibc/ipk
if [ ! -d $SOURCE_DIR ]; then
    echo "Error: Source packages not found. Did you run a build yet?"
    exit 1
fi
