SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `Mayhem`.`GST` CHANGE COLUMN `CarID` `CarID` VARCHAR(64) NOT NULL  ;

ALTER TABLE `Mayhem`.`Reader` CHANGE COLUMN `signalStrengthThreshold` `signalStrengthThreshold` INT(11) NOT NULL DEFAULT '-90'  ;

CREATE  TABLE IF NOT EXISTS `Mayhem`.`SchemaVersion` (
  `version` VARCHAR(40) NOT NULL ,
  `model` VARCHAR(255) NOT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci
COMMENT = 'Mayhem database schema version';

--
-- Dumping data for table `SchemaVersion`
--

LOCK TABLES `SchemaVersion` WRITE;
/*!40000 ALTER TABLE `SchemaVersion` DISABLE KEYS */;
DELETE FROM `SchemaVersion`;
INSERT INTO `SchemaVersion` VALUES ('1.0.0.0','attractionmodel');
/*!40000 ALTER TABLE `SchemaVersion` ENABLE KEYS */;
UNLOCK TABLES;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
