ALTER TABLE [dbo].[celebration_guest]
    ADD CONSTRAINT [PK_celebration_guest] PRIMARY KEY CLUSTERED ([celebrationId] ASC, [guestId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

