ALTER TABLE [dbo].[guest_address]
    ADD CONSTRAINT [PK_guest_info] PRIMARY KEY CLUSTERED ([guest_addressId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

