ALTER TABLE [dbo].[scheduledItem]
    ADD CONSTRAINT [PK_scheduledItem] PRIMARY KEY CLUSTERED ([scheduledItemId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

