ALTER TABLE [dbo].[guest_scheduledItem]
    ADD CONSTRAINT [PK_guest_scheduledItem] PRIMARY KEY CLUSTERED ([guest_scheduledItemId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

