ALTER TABLE [dbo].[guest_xband]
    ADD CONSTRAINT [PK_guest_xband] PRIMARY KEY CLUSTERED ([guestId] ASC, [xbandId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

