ALTER TABLE [dbo].[xband]
    ADD CONSTRAINT [AK_tapId] UNIQUE NONCLUSTERED ([tapId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

