ALTER TABLE [dbo].[IDMS_Type]
    ADD CONSTRAINT [PK_IDMS_Type] PRIMARY KEY CLUSTERED ([IDMSTypeId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

