#!/bin/sh

APP=/mayhem/reader
PID=/var/run/monitor-reader.pid
MONITOR=/mayhem/monitor-reader

dap_reader_start() {
    echo -n "Starting reader application: "

    # install pwm driver
    insmod /lib/modules/$(uname -r)/extra/pwm.ko frequency=100 2>/dev/null

    # enable core-dumps
    ulimit -c unlimited

    # run the app
    cd /mayhem
    start-stop-daemon --start --quiet --background --pidfile $PID -m --exec sh -- $MONITOR
    echo "."
}

dap_reader_stop() {
    echo -n "Stopping reader application: "
    start-stop-daemon --stop --quiet --pidfile $PID && killall reader
    echo "."
}

case "$1" in
	start)    dap_reader_start ;;
	stop)     dap_reader_stop ;;
	restart)  : ;; # Called by opkg install - ignore
	*)
	    echo "Usage: /etc/init.d/reader {start|stop}"
	    exit 1
	;;
esac
