bcp dbo.guest out dbo.guest.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.xband out dbo.xband.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.source_system_link out dbo.source_system_link.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.guest_xband out dbo.guest_xband.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.celebration out dbo.celebration.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.celebration_guest out dbo.celebration_guest.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.xband_request out dbo.xband_request.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.guest_xband_request out dbo.guest_xband_request.dat -n -E -S %1 -d %2 -U %3 -P %4
bcp dbo.xband_state out dbo.xband_state.dat -n -E -S %1 -d %2 -U %3 -P %4