#!/bin/sh

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1
NTPDATE_CONF='/etc/default/ntpdate'

case "$1" in
	deconfig)
		;;

	renew|bound)
		for i in $ntpsrv ; do
			echo adding ntp $i
			echo NTPSERVERS=\"$i\" > $NTPDATE_CONF
		done
		;;
esac

exit 0
