ALTER TABLE [gxp].[BusinessEventType]
    ADD CONSTRAINT [PK_BusinessEventType] PRIMARY KEY CLUSTERED ([BusinessEventTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

