ALTER TABLE [gxp].[BusinessEventType]
    ADD CONSTRAINT [AK_BusinessEventType] UNIQUE NONCLUSTERED ([BusinessEventType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

