ALTER TABLE [gxp].[BlueLaneEvent]
    ADD CONSTRAINT [PK_RedemptionEvent] PRIMARY KEY CLUSTERED ([BlueLaneEventID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

