ALTER TABLE [gxp].[BusinessEvent]
    ADD CONSTRAINT [PK_BusinessEvent] PRIMARY KEY CLUSTERED ([BusinessEventID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

