ALTER TABLE [gxp].[AppointmentStatus]
    ADD CONSTRAINT [AK_AppointmentStatus_AppointmentStatus] UNIQUE NONCLUSTERED ([AppointmentStatus] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

