ALTER TABLE [gxp].[EntitlementStatus]
    ADD CONSTRAINT [PK_EntitlementStatus] PRIMARY KEY CLUSTERED ([EntitlementStatusID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

