ALTER TABLE [gxp].[AppointmentReason]
    ADD CONSTRAINT [PK_AppointmentReason] PRIMARY KEY CLUSTERED ([AppointmentReasonID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

