ALTER TABLE [gxp].[AppointmentStatus]
    ADD CONSTRAINT [PK_AppointmentStatus] PRIMARY KEY CLUSTERED ([AppointmentStatusID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

