ALTER TABLE [gxp].[RedemptionEvent]
    ADD CONSTRAINT [PK_RedemptionEvent_1] PRIMARY KEY CLUSTERED ([RedemptionEventID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

