ALTER TABLE [gxp].[BusinessEventSubType]
    ADD CONSTRAINT [PK_BusinessEventSubType] PRIMARY KEY CLUSTERED ([BusinessEventSubTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

