ALTER TABLE [gxp].[AppointmentReason]
    ADD CONSTRAINT [AK_AppointmentReason_AppointmentReason] UNIQUE NONCLUSTERED ([AppointmentReason] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

