//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IDMSLib
{
    public partial class guest_infoPOCO
    {
        #region Primitive Properties
    
        public virtual long guestInfoId
        {
            get;
            set;
        }
    
        public virtual long guestId
        {
            get;
            set;
        }
    
        public virtual string cellPhone
        {
            get;
            set;
        }
    
        public virtual string address1
        {
            get;
            set;
        }
    
        public virtual string address2
        {
            get;
            set;
        }
    
        public virtual string city
        {
            get;
            set;
        }
    
        public virtual string state
        {
            get;
            set;
        }
    
        public virtual string countryCode
        {
            get;
            set;
        }
    
        public virtual string postalCode
        {
            get;
            set;
        }
    
        public virtual string createdBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> createdDate
        {
            get;
            set;
        }
    
        public virtual string updatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> updatedDate
        {
            get;
            set;
        }
    
        public virtual string sourceId
        {
            get;
            set;
        }
    
        public virtual Nullable<long> sourceTypeId
        {
            get;
            set;
        }

        #endregion
    }
}
