//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IDMSLib
{
    public partial class guest_xbandPOCO
    {
        #region Primitive Properties
    
        public virtual long guest_xband_id
        {
            get;
            set;
        }
    
        public virtual Nullable<long> guestId
        {
            get;
            set;
        }
    
        public virtual Nullable<long> xbandId
        {
            get;
            set;
        }
    
        public virtual string createdBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> createdDate
        {
            get;
            set;
        }
    
        public virtual string updatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> updatedDate
        {
            get;
            set;
        }
    
        public virtual string sourceId
        {
            get;
            set;
        }
    
        public virtual Nullable<long> sourceTypeId
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> active
        {
            get;
            set;
        }

        #endregion
    }
}
