//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("XViewModel", "FK_guest_info_guest", "guest", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IDMSLib.guest), "guest_info", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IDMSLib.guest_info), true)]
[assembly: EdmRelationshipAttribute("XViewModel", "FK_guest_xband_guest", "guest", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IDMSLib.guest), "guest_xband", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IDMSLib.guest_xband), true)]
[assembly: EdmRelationshipAttribute("XViewModel", "FK_guest_xband_xband", "xband", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IDMSLib.xband), "guest_xband", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IDMSLib.guest_xband), true)]

#endregion

namespace IDMSLib
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class XViewEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new XViewEntities object using the connection string found in the 'XViewEntities' section of the application configuration file.
        /// </summary>
        public XViewEntities() : base("name=XViewEntities", "XViewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XViewEntities object.
        /// </summary>
        public XViewEntities(string connectionString) : base(connectionString, "XViewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new XViewEntities object.
        /// </summary>
        public XViewEntities(EntityConnection connection) : base(connection, "XViewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<guest> guests
        {
            get
            {
                if ((_guests == null))
                {
                    _guests = base.CreateObjectSet<guest>("guests");
                }
                return _guests;
            }
        }
        private ObjectSet<guest> _guests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<guest_info> guest_info
        {
            get
            {
                if ((_guest_info == null))
                {
                    _guest_info = base.CreateObjectSet<guest_info>("guest_info");
                }
                return _guest_info;
            }
        }
        private ObjectSet<guest_info> _guest_info;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<guest_xband> guest_xband
        {
            get
            {
                if ((_guest_xband == null))
                {
                    _guest_xband = base.CreateObjectSet<guest_xband>("guest_xband");
                }
                return _guest_xband;
            }
        }
        private ObjectSet<guest_xband> _guest_xband;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<source_type> source_type
        {
            get
            {
                if ((_source_type == null))
                {
                    _source_type = base.CreateObjectSet<source_type>("source_type");
                }
                return _source_type;
            }
        }
        private ObjectSet<source_type> _source_type;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<xband> xbands
        {
            get
            {
                if ((_xbands == null))
                {
                    _xbands = base.CreateObjectSet<xband>("xbands");
                }
                return _xbands;
            }
        }
        private ObjectSet<xband> _xbands;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the guests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToguests(guest guest)
        {
            base.AddObject("guests", guest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the guest_info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToguest_info(guest_info guest_info)
        {
            base.AddObject("guest_info", guest_info);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the guest_xband EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToguest_xband(guest_xband guest_xband)
        {
            base.AddObject("guest_xband", guest_xband);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the source_type EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosource_type(source_type source_type)
        {
            base.AddObject("source_type", source_type);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the xbands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToxbands(xband xband)
        {
            base.AddObject("xbands", xband);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XViewModel", Name="guest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class guest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new guest object.
        /// </summary>
        /// <param name="guestId">Initial value of the guestId property.</param>
        public static guest Createguest(global::System.Int64 guestId)
        {
            guest guest = new guest();
            guest.guestId = guestId;
            return guest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 guestId
        {
            get
            {
                return _guestId;
            }
            set
            {
                if (_guestId != value)
                {
                    OnguestIdChanging(value);
                    ReportPropertyChanging("guestId");
                    _guestId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("guestId");
                    OnguestIdChanged();
                }
            }
        }
        private global::System.Int64 _guestId;
        partial void OnguestIdChanging(global::System.Int64 value);
        partial void OnguestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _active;
        partial void OnactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updatedBy
        {
            get
            {
                return _updatedBy;
            }
            set
            {
                OnupdatedByChanging(value);
                ReportPropertyChanging("updatedBy");
                _updatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updatedBy");
                OnupdatedByChanged();
            }
        }
        private global::System.String _updatedBy;
        partial void OnupdatedByChanging(global::System.String value);
        partial void OnupdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updatedDate
        {
            get
            {
                return _updatedDate;
            }
            set
            {
                OnupdatedDateChanging(value);
                ReportPropertyChanging("updatedDate");
                _updatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updatedDate");
                OnupdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _updatedDate;
        partial void OnupdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnupdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sourceId
        {
            get
            {
                return _sourceId;
            }
            set
            {
                OnsourceIdChanging(value);
                ReportPropertyChanging("sourceId");
                _sourceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sourceId");
                OnsourceIdChanged();
            }
        }
        private global::System.String _sourceId;
        partial void OnsourceIdChanging(global::System.String value);
        partial void OnsourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> sourceTypeId
        {
            get
            {
                return _sourceTypeId;
            }
            set
            {
                OnsourceTypeIdChanging(value);
                ReportPropertyChanging("sourceTypeId");
                _sourceTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sourceTypeId");
                OnsourceTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _sourceTypeId;
        partial void OnsourceTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnsourceTypeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XViewModel", "FK_guest_info_guest", "guest_info")]
        public EntityCollection<guest_info> guest_info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<guest_info>("XViewModel.FK_guest_info_guest", "guest_info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<guest_info>("XViewModel.FK_guest_info_guest", "guest_info", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XViewModel", "FK_guest_xband_guest", "guest_xband")]
        public EntityCollection<guest_xband> guest_xband
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<guest_xband>("XViewModel.FK_guest_xband_guest", "guest_xband");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<guest_xband>("XViewModel.FK_guest_xband_guest", "guest_xband", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XViewModel", Name="guest_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class guest_info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new guest_info object.
        /// </summary>
        /// <param name="guestInfoId">Initial value of the guestInfoId property.</param>
        /// <param name="guestId">Initial value of the guestId property.</param>
        public static guest_info Createguest_info(global::System.Int64 guestInfoId, global::System.Int64 guestId)
        {
            guest_info guest_info = new guest_info();
            guest_info.guestInfoId = guestInfoId;
            guest_info.guestId = guestId;
            return guest_info;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 guestInfoId
        {
            get
            {
                return _guestInfoId;
            }
            set
            {
                if (_guestInfoId != value)
                {
                    OnguestInfoIdChanging(value);
                    ReportPropertyChanging("guestInfoId");
                    _guestInfoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("guestInfoId");
                    OnguestInfoIdChanged();
                }
            }
        }
        private global::System.Int64 _guestInfoId;
        partial void OnguestInfoIdChanging(global::System.Int64 value);
        partial void OnguestInfoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 guestId
        {
            get
            {
                return _guestId;
            }
            set
            {
                OnguestIdChanging(value);
                ReportPropertyChanging("guestId");
                _guestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("guestId");
                OnguestIdChanged();
            }
        }
        private global::System.Int64 _guestId;
        partial void OnguestIdChanging(global::System.Int64 value);
        partial void OnguestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cellPhone
        {
            get
            {
                return _cellPhone;
            }
            set
            {
                OncellPhoneChanging(value);
                ReportPropertyChanging("cellPhone");
                _cellPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cellPhone");
                OncellPhoneChanged();
            }
        }
        private global::System.String _cellPhone;
        partial void OncellPhoneChanging(global::System.String value);
        partial void OncellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address1
        {
            get
            {
                return _address1;
            }
            set
            {
                Onaddress1Changing(value);
                ReportPropertyChanging("address1");
                _address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address1");
                Onaddress1Changed();
            }
        }
        private global::System.String _address1;
        partial void Onaddress1Changing(global::System.String value);
        partial void Onaddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address2
        {
            get
            {
                return _address2;
            }
            set
            {
                Onaddress2Changing(value);
                ReportPropertyChanging("address2");
                _address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address2");
                Onaddress2Changed();
            }
        }
        private global::System.String _address2;
        partial void Onaddress2Changing(global::System.String value);
        partial void Onaddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String countryCode
        {
            get
            {
                return _countryCode;
            }
            set
            {
                OncountryCodeChanging(value);
                ReportPropertyChanging("countryCode");
                _countryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("countryCode");
                OncountryCodeChanged();
            }
        }
        private global::System.String _countryCode;
        partial void OncountryCodeChanging(global::System.String value);
        partial void OncountryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String postalCode
        {
            get
            {
                return _postalCode;
            }
            set
            {
                OnpostalCodeChanging(value);
                ReportPropertyChanging("postalCode");
                _postalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("postalCode");
                OnpostalCodeChanged();
            }
        }
        private global::System.String _postalCode;
        partial void OnpostalCodeChanging(global::System.String value);
        partial void OnpostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updatedBy
        {
            get
            {
                return _updatedBy;
            }
            set
            {
                OnupdatedByChanging(value);
                ReportPropertyChanging("updatedBy");
                _updatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updatedBy");
                OnupdatedByChanged();
            }
        }
        private global::System.String _updatedBy;
        partial void OnupdatedByChanging(global::System.String value);
        partial void OnupdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updatedDate
        {
            get
            {
                return _updatedDate;
            }
            set
            {
                OnupdatedDateChanging(value);
                ReportPropertyChanging("updatedDate");
                _updatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updatedDate");
                OnupdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _updatedDate;
        partial void OnupdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnupdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sourceId
        {
            get
            {
                return _sourceId;
            }
            set
            {
                OnsourceIdChanging(value);
                ReportPropertyChanging("sourceId");
                _sourceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sourceId");
                OnsourceIdChanged();
            }
        }
        private global::System.String _sourceId;
        partial void OnsourceIdChanging(global::System.String value);
        partial void OnsourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> sourceTypeId
        {
            get
            {
                return _sourceTypeId;
            }
            set
            {
                OnsourceTypeIdChanging(value);
                ReportPropertyChanging("sourceTypeId");
                _sourceTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sourceTypeId");
                OnsourceTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _sourceTypeId;
        partial void OnsourceTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnsourceTypeIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XViewModel", Name="guest_xband")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class guest_xband : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new guest_xband object.
        /// </summary>
        /// <param name="guest_xband_id">Initial value of the guest_xband_id property.</param>
        public static guest_xband Createguest_xband(global::System.Int64 guest_xband_id)
        {
            guest_xband guest_xband = new guest_xband();
            guest_xband.guest_xband_id = guest_xband_id;
            return guest_xband;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 guest_xband_id
        {
            get
            {
                return _guest_xband_id;
            }
            set
            {
                if (_guest_xband_id != value)
                {
                    Onguest_xband_idChanging(value);
                    ReportPropertyChanging("guest_xband_id");
                    _guest_xband_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("guest_xband_id");
                    Onguest_xband_idChanged();
                }
            }
        }
        private global::System.Int64 _guest_xband_id;
        partial void Onguest_xband_idChanging(global::System.Int64 value);
        partial void Onguest_xband_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> guestId
        {
            get
            {
                return _guestId;
            }
            set
            {
                OnguestIdChanging(value);
                ReportPropertyChanging("guestId");
                _guestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("guestId");
                OnguestIdChanged();
            }
        }
        private Nullable<global::System.Int64> _guestId;
        partial void OnguestIdChanging(Nullable<global::System.Int64> value);
        partial void OnguestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> xbandId
        {
            get
            {
                return _xbandId;
            }
            set
            {
                OnxbandIdChanging(value);
                ReportPropertyChanging("xbandId");
                _xbandId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("xbandId");
                OnxbandIdChanged();
            }
        }
        private Nullable<global::System.Int64> _xbandId;
        partial void OnxbandIdChanging(Nullable<global::System.Int64> value);
        partial void OnxbandIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updatedBy
        {
            get
            {
                return _updatedBy;
            }
            set
            {
                OnupdatedByChanging(value);
                ReportPropertyChanging("updatedBy");
                _updatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updatedBy");
                OnupdatedByChanged();
            }
        }
        private global::System.String _updatedBy;
        partial void OnupdatedByChanging(global::System.String value);
        partial void OnupdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updatedDate
        {
            get
            {
                return _updatedDate;
            }
            set
            {
                OnupdatedDateChanging(value);
                ReportPropertyChanging("updatedDate");
                _updatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updatedDate");
                OnupdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _updatedDate;
        partial void OnupdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnupdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sourceId
        {
            get
            {
                return _sourceId;
            }
            set
            {
                OnsourceIdChanging(value);
                ReportPropertyChanging("sourceId");
                _sourceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sourceId");
                OnsourceIdChanged();
            }
        }
        private global::System.String _sourceId;
        partial void OnsourceIdChanging(global::System.String value);
        partial void OnsourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> sourceTypeId
        {
            get
            {
                return _sourceTypeId;
            }
            set
            {
                OnsourceTypeIdChanging(value);
                ReportPropertyChanging("sourceTypeId");
                _sourceTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sourceTypeId");
                OnsourceTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _sourceTypeId;
        partial void OnsourceTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnsourceTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _active;
        partial void OnactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnactiveChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XViewModel", Name="source_type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class source_type : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new source_type object.
        /// </summary>
        /// <param name="sourceTypeId">Initial value of the sourceTypeId property.</param>
        public static source_type Createsource_type(global::System.Int64 sourceTypeId)
        {
            source_type source_type = new source_type();
            source_type.sourceTypeId = sourceTypeId;
            return source_type;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 sourceTypeId
        {
            get
            {
                return _sourceTypeId;
            }
            set
            {
                if (_sourceTypeId != value)
                {
                    OnsourceTypeIdChanging(value);
                    ReportPropertyChanging("sourceTypeId");
                    _sourceTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sourceTypeId");
                    OnsourceTypeIdChanged();
                }
            }
        }
        private global::System.Int64 _sourceTypeId;
        partial void OnsourceTypeIdChanging(global::System.Int64 value);
        partial void OnsourceTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sourceTypeName
        {
            get
            {
                return _sourceTypeName;
            }
            set
            {
                OnsourceTypeNameChanging(value);
                ReportPropertyChanging("sourceTypeName");
                _sourceTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sourceTypeName");
                OnsourceTypeNameChanged();
            }
        }
        private global::System.String _sourceTypeName;
        partial void OnsourceTypeNameChanging(global::System.String value);
        partial void OnsourceTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updatedBy
        {
            get
            {
                return _updatedBy;
            }
            set
            {
                OnupdatedByChanging(value);
                ReportPropertyChanging("updatedBy");
                _updatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updatedBy");
                OnupdatedByChanged();
            }
        }
        private global::System.String _updatedBy;
        partial void OnupdatedByChanging(global::System.String value);
        partial void OnupdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updatedDate
        {
            get
            {
                return _updatedDate;
            }
            set
            {
                OnupdatedDateChanging(value);
                ReportPropertyChanging("updatedDate");
                _updatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updatedDate");
                OnupdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _updatedDate;
        partial void OnupdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnupdatedDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="XViewModel", Name="xband")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class xband : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new xband object.
        /// </summary>
        /// <param name="xbandId">Initial value of the xbandId property.</param>
        public static xband Createxband(global::System.Int64 xbandId)
        {
            xband xband = new xband();
            xband.xbandId = xbandId;
            return xband;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 xbandId
        {
            get
            {
                return _xbandId;
            }
            set
            {
                if (_xbandId != value)
                {
                    OnxbandIdChanging(value);
                    ReportPropertyChanging("xbandId");
                    _xbandId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("xbandId");
                    OnxbandIdChanged();
                }
            }
        }
        private global::System.Int64 _xbandId;
        partial void OnxbandIdChanging(global::System.Int64 value);
        partial void OnxbandIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> bandId
        {
            get
            {
                return _bandId;
            }
            set
            {
                OnbandIdChanging(value);
                ReportPropertyChanging("bandId");
                _bandId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bandId");
                OnbandIdChanged();
            }
        }
        private Nullable<global::System.Int64> _bandId;
        partial void OnbandIdChanging(Nullable<global::System.Int64> value);
        partial void OnbandIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> longRangeId
        {
            get
            {
                return _longRangeId;
            }
            set
            {
                OnlongRangeIdChanging(value);
                ReportPropertyChanging("longRangeId");
                _longRangeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("longRangeId");
                OnlongRangeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _longRangeId;
        partial void OnlongRangeIdChanging(Nullable<global::System.Int64> value);
        partial void OnlongRangeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> tapId
        {
            get
            {
                return _tapId;
            }
            set
            {
                OntapIdChanging(value);
                ReportPropertyChanging("tapId");
                _tapId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tapId");
                OntapIdChanged();
            }
        }
        private Nullable<global::System.Int64> _tapId;
        partial void OntapIdChanging(Nullable<global::System.Int64> value);
        partial void OntapIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> secureId
        {
            get
            {
                return _secureId;
            }
            set
            {
                OnsecureIdChanging(value);
                ReportPropertyChanging("secureId");
                _secureId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("secureId");
                OnsecureIdChanged();
            }
        }
        private Nullable<global::System.Int64> _secureId;
        partial void OnsecureIdChanging(Nullable<global::System.Int64> value);
        partial void OnsecureIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private Nullable<global::System.Int64> _UID;
        partial void OnUIDChanging(Nullable<global::System.Int64> value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bandFriendlyName
        {
            get
            {
                return _bandFriendlyName;
            }
            set
            {
                OnbandFriendlyNameChanging(value);
                ReportPropertyChanging("bandFriendlyName");
                _bandFriendlyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bandFriendlyName");
                OnbandFriendlyNameChanged();
            }
        }
        private global::System.String _bandFriendlyName;
        partial void OnbandFriendlyNameChanging(global::System.String value);
        partial void OnbandFriendlyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String printedName
        {
            get
            {
                return _printedName;
            }
            set
            {
                OnprintedNameChanging(value);
                ReportPropertyChanging("printedName");
                _printedName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("printedName");
                OnprintedNameChanged();
            }
        }
        private global::System.String _printedName;
        partial void OnprintedNameChanging(global::System.String value);
        partial void OnprintedNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _active;
        partial void OnactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private global::System.String _createdBy;
        partial void OncreatedByChanging(global::System.String value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String updatedBy
        {
            get
            {
                return _updatedBy;
            }
            set
            {
                OnupdatedByChanging(value);
                ReportPropertyChanging("updatedBy");
                _updatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("updatedBy");
                OnupdatedByChanged();
            }
        }
        private global::System.String _updatedBy;
        partial void OnupdatedByChanging(global::System.String value);
        partial void OnupdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updatedDate
        {
            get
            {
                return _updatedDate;
            }
            set
            {
                OnupdatedDateChanging(value);
                ReportPropertyChanging("updatedDate");
                _updatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updatedDate");
                OnupdatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _updatedDate;
        partial void OnupdatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnupdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sourceId
        {
            get
            {
                return _sourceId;
            }
            set
            {
                OnsourceIdChanging(value);
                ReportPropertyChanging("sourceId");
                _sourceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sourceId");
                OnsourceIdChanged();
            }
        }
        private global::System.String _sourceId;
        partial void OnsourceIdChanging(global::System.String value);
        partial void OnsourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> sourceTypeId
        {
            get
            {
                return _sourceTypeId;
            }
            set
            {
                OnsourceTypeIdChanging(value);
                ReportPropertyChanging("sourceTypeId");
                _sourceTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sourceTypeId");
                OnsourceTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _sourceTypeId;
        partial void OnsourceTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnsourceTypeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("XViewModel", "FK_guest_xband_xband", "guest_xband")]
        public EntityCollection<guest_xband> guest_xband
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<guest_xband>("XViewModel.FK_guest_xband_xband", "guest_xband");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<guest_xband>("XViewModel.FK_guest_xband_xband", "guest_xband", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
