ALTER TABLE [dbo].[DailyPilotReport]
    ADD CONSTRAINT [PK_DailyPilotReport] PRIMARY KEY CLUSTERED ([reportId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

