ALTER TABLE [dbo].[schema_version]
    ADD CONSTRAINT [PK_SchemaVersion] PRIMARY KEY CLUSTERED ([schema_version_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

