ALTER TABLE [dbo].[PerformanceMetricDesc]
    ADD CONSTRAINT [PK_PerformanceMetricDesc] PRIMARY KEY CLUSTERED ([PerformanceMetricDescID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

