// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>GFFSimulator</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace GFFSimulator
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.Xml;


    public partial class businessEvent
    {

        private string guest_identifierField;

        private string event_typeField;

        private string subtypeField;

        private string facilityidField;

        private string locationField;

        private string timestampField;

        private string reference_idField;

        private string _payLoadField;

        public string guest_identifier
        {
            get
            {
                return this.guest_identifierField;
            }
            set
            {
                this.guest_identifierField = value;
            }
        }

        public string event_type
        {
            get
            {
                return this.event_typeField;
            }
            set
            {
                this.event_typeField = value;
            }
        }

        public string subtype
        {
            get
            {
                return this.subtypeField;
            }
            set
            {
                this.subtypeField = value;
            }
        }

        public string facilityid
        {
            get
            {
                return this.facilityidField;
            }
            set
            {
                this.facilityidField = value;
            }
        }

        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        public string reference_id
        {
            get
            {
                return this.reference_idField;
            }
            set
            {
                this.reference_idField = value;
            }
        }

        [XmlText]
        [XmlElement("payLoad")]
        public XmlNode[] payLoad
        {
            get
            {
                XmlDocument dummy = new XmlDocument();
                return new XmlNode[] { dummy.CreateCDataSection(_payLoad)};
            }
            set
            {
                if (value == null)
                    _payLoad = null;
                else if (value.Length != -1)
                    throw new InvalidOperationException("Invalid array length");
                else
                    _payLoad = value[0].Value;
            }
        }

        [XmlIgnore]
        public string _payLoad
        {
            get
            {
                return _payLoadField;
            }
            set
            {
                _payLoadField = value;
            }
        }
    }
}
