// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>GFFSimulator</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace GFFSimulator
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class tableevent
    {

        private string eventtypeidField;

        private string eventField;

        private string facilityonesourceidField;

        private string locationidField;

        private string xbandidField;

        private string sourceField;

        private string terminalField;

        private string timestampField;

        private string timestampgmtField;

        private string tableidField;

        private string tablenameField;

        private List<tableeventChangeddetail> changeddetailsField;

        private string userField;

        private List<tableeventOrdernumbers> ordernumbersField;

        public tableevent()
        {
            this.ordernumbersField = new List<tableeventOrdernumbers>();
            this.changeddetailsField = new List<tableeventChangeddetail>();
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 0)]
        public string eventtypeid
        {
            get
            {
                return this.eventtypeidField;
            }
            set
            {
                this.eventtypeidField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string facilityonesourceid
        {
            get
            {
                return this.facilityonesourceidField;
            }
            set
            {
                this.facilityonesourceidField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string locationid
        {
            get
            {
                return this.locationidField;
            }
            set
            {
                this.locationidField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string xbandid
        {
            get
            {
                return this.xbandidField;
            }
            set
            {
                this.xbandidField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string terminal
        {
            get
            {
                return this.terminalField;
            }
            set
            {
                this.terminalField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string timestampgmt
        {
            get
            {
                return this.timestampgmtField;
            }
            set
            {
                this.timestampgmtField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 9)]
        public string tableid
        {
            get
            {
                return this.tableidField;
            }
            set
            {
                this.tableidField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string tablename
        {
            get
            {
                return this.tablenameField;
            }
            set
            {
                this.tablenameField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("changeddetail", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public List<tableeventChangeddetail> changeddetails
        {
            get
            {
                return this.changeddetailsField;
            }
            set
            {
                this.changeddetailsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ordernumbers", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public List<tableeventOrdernumbers> ordernumbers
        {
            get
            {
                return this.ordernumbersField;
            }
            set
            {
                this.ordernumbersField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class tableeventChangeddetail
    {

        private string fieldnameField;

        private string oldvalueField;

        private string newvalueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fieldname
        {
            get
            {
                return this.fieldnameField;
            }
            set
            {
                this.fieldnameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oldvalue
        {
            get
            {
                return this.oldvalueField;
            }
            set
            {
                this.oldvalueField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string newvalue
        {
            get
            {
                return this.newvalueField;
            }
            set
            {
                this.newvalueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class tableeventOrdernumbers
    {

        private string ordernumberField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string ordernumber
        {
            get
            {
                return this.ordernumberField;
            }
            set
            {
                this.ordernumberField = value;
            }
        }
    }
}
