// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>GFFSimulator</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace GFFSimulator
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class tapevent
    {

        private string eventtypeidField;

        private string eventField;

        private string facilityonesourceidField;

        private string xbandidField;

        private string sourceField;

        private string timestampField;

        private string timestampgmtField;

        private string ordernumberField;

        private string gxplinkidField;

        private string terminalField;

        private string laneField;

        private string xpassidField;

        private string partysizeField;

        private string sourcetypeField;

        private bool isbluelanedField;

        public string eventtypeid
        {
            get
            {
                return this.eventtypeidField;
            }
            set
            {
                this.eventtypeidField = value;
            }
        }

        public string @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }

        public string facilityonesourceid
        {
            get
            {
                return this.facilityonesourceidField;
            }
            set
            {
                this.facilityonesourceidField = value;
            }
        }

        public string xbandid
        {
            get
            {
                return this.xbandidField;
            }
            set
            {
                this.xbandidField = value;
            }
        }

        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        public string timestampgmt
        {
            get
            {
                return this.timestampgmtField;
            }
            set
            {
                this.timestampgmtField = value;
            }
        }

        public string ordernumber
        {
            get
            {
                return this.ordernumberField;
            }
            set
            {
                this.ordernumberField = value;
            }
        }

        public string gxplinkid
        {
            get
            {
                return this.gxplinkidField;
            }
            set
            {
                this.gxplinkidField = value;
            }
        }

        public string terminal
        {
            get
            {
                return this.terminalField;
            }
            set
            {
                this.terminalField = value;
            }
        }

        public string lane
        {
            get
            {
                return this.laneField;
            }
            set
            {
                this.laneField = value;
            }
        }

        public string xpassid
        {
            get
            {
                return this.xpassidField;
            }
            set
            {
                this.xpassidField = value;
            }
        }

        public string partysize
        {
            get
            {
                return this.partysizeField;
            }
            set
            {
                this.partysizeField = value;
            }
        }

        public string sourcetype
        {
            get
            {
                return this.sourcetypeField;
            }
            set
            {
                this.sourcetypeField = value;
            }
        }

        public bool isbluelaned
        {
            get
            {
                return this.isbluelanedField;
            }
            set
            {
                this.isbluelanedField = value;
            }
        }
    }
}
