ALTER TABLE [rdr].[Attraction]
    ADD CONSTRAINT [PK_Attraction] PRIMARY KEY CLUSTERED ([AttractionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

