ALTER TABLE [rdr].[BandType]
    ADD CONSTRAINT [AK_BandType_BandTypeName] UNIQUE NONCLUSTERED ([BandTypeName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

