ALTER TABLE [rdr].[Attraction]
    ADD CONSTRAINT [AK_Attraction] UNIQUE NONCLUSTERED ([AttractionName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

