ALTER TABLE [rdr].[MetricType]
    ADD CONSTRAINT [PK_MetricType] PRIMARY KEY CLUSTERED ([MetricTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

