ALTER TABLE [rdr].[Facility]
    ADD CONSTRAINT [PK_Facility] PRIMARY KEY CLUSTERED ([FacilityID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

