ALTER TABLE [rdr].[MetricType]
    ADD CONSTRAINT [AK_MetricType] UNIQUE NONCLUSTERED ([MetricTypeName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

