ALTER TABLE [rdr].[BandType]
    ADD CONSTRAINT [PK_BandType] PRIMARY KEY CLUSTERED ([BandTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

