ALTER TABLE [rdr].[FacilityType]
    ADD CONSTRAINT [PK_FacilityType] PRIMARY KEY CLUSTERED ([FacilityTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

