package com.disney.xband.lib.xbrapi;

import java.util.Date;

/*
 * This class represents an event generated by the WDI Disney
 * readers that detect a vehicle at the reader. One event is 
 * received per vehicle at the reader.
 * 
 * The reader name is constructed by concatenating "sceneid-locationid".
 */
public class AVMSEvent extends XbrEvent
{
	private String vehicleid;
	private String attractionid;
	private String sceneid;
	private String locationid;
	private Integer confidence;
	private Date readerEventTime; 
	
	public static AVMSEvent fromRawAVMSEvent(RawAVMSEvent src)
	{
		AVMSEvent ret = new AVMSEvent();
		
		// Since we have no way of synchronizing clocks with the AVMS system
		// it is safest to us the current date time for the event rather than
		// rely on the time sent from the AVMS system.
		
		ret.setTime(new Date());
		
		ret.vehicleid = src.getVehicleid();
		ret.attractionid = src.getAttractionid();
		ret.sceneid = src.getSceneid();
		ret.locationid = src.getLocationid();
		ret.confidence = src.getConfidence();
		ret.readerEventTime = src.getTime();
		
		// make up some monotonically increasing number
		ret.setEno(ret.getTime().getTime());
		// compose reader name from sceneid and locationid
		ret.setReaderName(ret.sceneid + "-" + ret.locationid);
		ret.setType(XbrEventType.VID);
		
		return ret;
	}
	
	@Override
	public String getID()
	{
		return vehicleid;
	}

	public String getVehicleid()
	{
		return vehicleid;
	}

	public void setVehicleid(String vehicleid)
	{
		this.vehicleid = vehicleid;
	}

	public String getAttractionid()
	{
		return attractionid;
	}

	public void setAttractionid(String attractionid)
	{
		this.attractionid = attractionid;
	}

	public String getSceneid()
	{
		return sceneid;
	}

	public void setSceneid(String sceneid)
	{
		this.sceneid = sceneid;
	}

	public String getLocationid()
	{
		return locationid;
	}

	public void setLocationid(String locationid)
	{
		this.locationid = locationid;
	}

	public Integer getConfidence()
	{
		return confidence;
	}

	public void setConfidence(Integer confidence)
	{
		this.confidence = confidence;
	}

	public Date getReaderEventTime()
	{
		return readerEventTime;
	}

	public void setReaderEventTime(Date readerEventTime)
	{
		this.readerEventTime = readerEventTime;
	}
}
