#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XViewLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="XView")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertguest(guest instance);
    partial void Updateguest(guest instance);
    partial void Deleteguest(guest instance);
    partial void Insertxband(xband instance);
    partial void Updatexband(xband instance);
    partial void Deletexband(xband instance);
    partial void Insertguest_info(guest_info instance);
    partial void Updateguest_info(guest_info instance);
    partial void Deleteguest_info(guest_info instance);
    partial void Insertguest_xband(guest_xband instance);
    partial void Updateguest_xband(guest_xband instance);
    partial void Deleteguest_xband(guest_xband instance);
    partial void Insertsource_type(source_type instance);
    partial void Updatesource_type(source_type instance);
    partial void Deletesource_type(source_type instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::XViewLib.Properties.Settings.Default.XViewConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<guest> guests
		{
			get
			{
				return this.GetTable<guest>();
			}
		}
		
		public System.Data.Linq.Table<xband> xbands
		{
			get
			{
				return this.GetTable<xband>();
			}
		}
		
		public System.Data.Linq.Table<guest_info> guest_infos
		{
			get
			{
				return this.GetTable<guest_info>();
			}
		}
		
		public System.Data.Linq.Table<guest_xband> guest_xbands
		{
			get
			{
				return this.GetTable<guest_xband>();
			}
		}
		
		public System.Data.Linq.Table<source_type> source_types
		{
			get
			{
				return this.GetTable<source_type>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.guest")]
	public partial class guest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _guestId;
		
		private string _lastName;
		
		private string _firstName;
		
		private System.Nullable<bool> _active;
		
		private string _createdBy;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private string _updatedBy;
		
		private System.Nullable<System.DateTime> _updatedDate;
		
		private string _sourceId;
		
		private System.Nullable<long> _sourceTypeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnguestIdChanging(long value);
    partial void OnguestIdChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OncreatedByChanging(string value);
    partial void OncreatedByChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnupdatedByChanging(string value);
    partial void OnupdatedByChanged();
    partial void OnupdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedDateChanged();
    partial void OnsourceIdChanging(string value);
    partial void OnsourceIdChanged();
    partial void OnsourceTypeIdChanging(System.Nullable<long> value);
    partial void OnsourceTypeIdChanged();
    #endregion
		
		public guest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guestId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long guestId
		{
			get
			{
				return this._guestId;
			}
			set
			{
				if ((this._guestId != value))
				{
					this.OnguestIdChanging(value);
					this.SendPropertyChanging();
					this._guestId = value;
					this.SendPropertyChanged("guestId");
					this.OnguestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="NVarChar(200)")]
		public string lastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if ((this._lastName != value))
				{
					this.OnlastNameChanging(value);
					this.SendPropertyChanging();
					this._lastName = value;
					this.SendPropertyChanged("lastName");
					this.OnlastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="NVarChar(200)")]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdBy", DbType="NVarChar(200)")]
		public string createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				if ((this._createdBy != value))
				{
					this.OncreatedByChanging(value);
					this.SendPropertyChanging();
					this._createdBy = value;
					this.SendPropertyChanged("createdBy");
					this.OncreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(200)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this.OnupdatedByChanging(value);
					this.SendPropertyChanging();
					this._updatedBy = value;
					this.SendPropertyChanged("updatedBy");
					this.OnupdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this.OnupdatedDateChanging(value);
					this.SendPropertyChanging();
					this._updatedDate = value;
					this.SendPropertyChanged("updatedDate");
					this.OnupdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceId", DbType="NVarChar(200)")]
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				if ((this._sourceId != value))
				{
					this.OnsourceIdChanging(value);
					this.SendPropertyChanging();
					this._sourceId = value;
					this.SendPropertyChanged("sourceId");
					this.OnsourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceTypeId", DbType="BigInt")]
		public System.Nullable<long> sourceTypeId
		{
			get
			{
				return this._sourceTypeId;
			}
			set
			{
				if ((this._sourceTypeId != value))
				{
					this.OnsourceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._sourceTypeId = value;
					this.SendPropertyChanged("sourceTypeId");
					this.OnsourceTypeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.xband")]
	public partial class xband : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _xbandId;
		
		private System.Nullable<long> _bandId;
		
		private System.Nullable<long> _lrId;
		
		private System.Nullable<long> _tapId;
		
		private string _bandFriendlyName;
		
		private string _printedName;
		
		private System.Nullable<bool> _active;
		
		private string _createdBy;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private string _updatedBy;
		
		private System.Nullable<System.DateTime> _updatedDate;
		
		private string _sourceId;
		
		private System.Nullable<long> _sourceTypeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnxbandIdChanging(long value);
    partial void OnxbandIdChanged();
    partial void OnbandIdChanging(System.Nullable<long> value);
    partial void OnbandIdChanged();
    partial void OnlrIdChanging(System.Nullable<long> value);
    partial void OnlrIdChanged();
    partial void OntapIdChanging(System.Nullable<long> value);
    partial void OntapIdChanged();
    partial void OnbandFriendlyNameChanging(string value);
    partial void OnbandFriendlyNameChanged();
    partial void OnprintedNameChanging(string value);
    partial void OnprintedNameChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OncreatedByChanging(string value);
    partial void OncreatedByChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnupdatedByChanging(string value);
    partial void OnupdatedByChanged();
    partial void OnupdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedDateChanged();
    partial void OnsourceIdChanging(string value);
    partial void OnsourceIdChanged();
    partial void OnsourceTypeIdChanging(System.Nullable<long> value);
    partial void OnsourceTypeIdChanged();
    #endregion
		
		public xband()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xbandId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long xbandId
		{
			get
			{
				return this._xbandId;
			}
			set
			{
				if ((this._xbandId != value))
				{
					this.OnxbandIdChanging(value);
					this.SendPropertyChanging();
					this._xbandId = value;
					this.SendPropertyChanged("xbandId");
					this.OnxbandIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bandId", DbType="BigInt")]
		public System.Nullable<long> bandId
		{
			get
			{
				return this._bandId;
			}
			set
			{
				if ((this._bandId != value))
				{
					this.OnbandIdChanging(value);
					this.SendPropertyChanging();
					this._bandId = value;
					this.SendPropertyChanged("bandId");
					this.OnbandIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lrId", DbType="BigInt")]
		public System.Nullable<long> lrId
		{
			get
			{
				return this._lrId;
			}
			set
			{
				if ((this._lrId != value))
				{
					this.OnlrIdChanging(value);
					this.SendPropertyChanging();
					this._lrId = value;
					this.SendPropertyChanged("lrId");
					this.OnlrIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tapId", DbType="BigInt")]
		public System.Nullable<long> tapId
		{
			get
			{
				return this._tapId;
			}
			set
			{
				if ((this._tapId != value))
				{
					this.OntapIdChanging(value);
					this.SendPropertyChanging();
					this._tapId = value;
					this.SendPropertyChanged("tapId");
					this.OntapIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bandFriendlyName", DbType="NVarChar(50)")]
		public string bandFriendlyName
		{
			get
			{
				return this._bandFriendlyName;
			}
			set
			{
				if ((this._bandFriendlyName != value))
				{
					this.OnbandFriendlyNameChanging(value);
					this.SendPropertyChanging();
					this._bandFriendlyName = value;
					this.SendPropertyChanged("bandFriendlyName");
					this.OnbandFriendlyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_printedName", DbType="NVarChar(255)")]
		public string printedName
		{
			get
			{
				return this._printedName;
			}
			set
			{
				if ((this._printedName != value))
				{
					this.OnprintedNameChanging(value);
					this.SendPropertyChanging();
					this._printedName = value;
					this.SendPropertyChanged("printedName");
					this.OnprintedNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdBy", DbType="NVarChar(200)")]
		public string createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				if ((this._createdBy != value))
				{
					this.OncreatedByChanging(value);
					this.SendPropertyChanging();
					this._createdBy = value;
					this.SendPropertyChanged("createdBy");
					this.OncreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(200)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this.OnupdatedByChanging(value);
					this.SendPropertyChanging();
					this._updatedBy = value;
					this.SendPropertyChanged("updatedBy");
					this.OnupdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this.OnupdatedDateChanging(value);
					this.SendPropertyChanging();
					this._updatedDate = value;
					this.SendPropertyChanged("updatedDate");
					this.OnupdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceId", DbType="NVarChar(200)")]
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				if ((this._sourceId != value))
				{
					this.OnsourceIdChanging(value);
					this.SendPropertyChanging();
					this._sourceId = value;
					this.SendPropertyChanged("sourceId");
					this.OnsourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceTypeId", DbType="BigInt")]
		public System.Nullable<long> sourceTypeId
		{
			get
			{
				return this._sourceTypeId;
			}
			set
			{
				if ((this._sourceTypeId != value))
				{
					this.OnsourceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._sourceTypeId = value;
					this.SendPropertyChanged("sourceTypeId");
					this.OnsourceTypeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.guest_info")]
	public partial class guest_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _guestInfoId;
		
		private long _guestId;
		
		private string _cellPhone;
		
		private System.Nullable<System.DateTime> _birthdate;
		
		private string _address1;
		
		private string _address2;
		
		private string _city;
		
		private string _state;
		
		private string _countryCode;
		
		private string _postalCode;
		
		private string _createdBy;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private string _updatedBy;
		
		private System.Nullable<System.DateTime> _updatedDate;
		
		private string _sourceId;
		
		private System.Nullable<long> _sourceTypeId;
		
		private EntityRef<guest> _guest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnguestInfoIdChanging(long value);
    partial void OnguestInfoIdChanged();
    partial void OnguestIdChanging(long value);
    partial void OnguestIdChanged();
    partial void OncellPhoneChanging(string value);
    partial void OncellPhoneChanged();
    partial void OnbirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdateChanged();
    partial void Onaddress1Changing(string value);
    partial void Onaddress1Changed();
    partial void Onaddress2Changing(string value);
    partial void Onaddress2Changed();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OncountryCodeChanging(string value);
    partial void OncountryCodeChanged();
    partial void OnpostalCodeChanging(string value);
    partial void OnpostalCodeChanged();
    partial void OncreatedByChanging(string value);
    partial void OncreatedByChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnupdatedByChanging(string value);
    partial void OnupdatedByChanged();
    partial void OnupdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedDateChanged();
    partial void OnsourceIdChanging(string value);
    partial void OnsourceIdChanged();
    partial void OnsourceTypeIdChanging(System.Nullable<long> value);
    partial void OnsourceTypeIdChanged();
    #endregion
		
		public guest_info()
		{
			this._guest = default(EntityRef<guest>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guestInfoId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long guestInfoId
		{
			get
			{
				return this._guestInfoId;
			}
			set
			{
				if ((this._guestInfoId != value))
				{
					this.OnguestInfoIdChanging(value);
					this.SendPropertyChanging();
					this._guestInfoId = value;
					this.SendPropertyChanged("guestInfoId");
					this.OnguestInfoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guestId", DbType="BigInt NOT NULL")]
		public long guestId
		{
			get
			{
				return this._guestId;
			}
			set
			{
				if ((this._guestId != value))
				{
					if (this._guest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnguestIdChanging(value);
					this.SendPropertyChanging();
					this._guestId = value;
					this.SendPropertyChanged("guestId");
					this.OnguestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cellPhone", DbType="NVarChar(15)")]
		public string cellPhone
		{
			get
			{
				return this._cellPhone;
			}
			set
			{
				if ((this._cellPhone != value))
				{
					this.OncellPhoneChanging(value);
					this.SendPropertyChanging();
					this._cellPhone = value;
					this.SendPropertyChanged("cellPhone");
					this.OncellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="Date")]
		public System.Nullable<System.DateTime> birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this.OnbirthdateChanging(value);
					this.SendPropertyChanging();
					this._birthdate = value;
					this.SendPropertyChanged("birthdate");
					this.OnbirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address1", DbType="NVarChar(200)")]
		public string address1
		{
			get
			{
				return this._address1;
			}
			set
			{
				if ((this._address1 != value))
				{
					this.Onaddress1Changing(value);
					this.SendPropertyChanging();
					this._address1 = value;
					this.SendPropertyChanged("address1");
					this.Onaddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address2", DbType="NVarChar(200)")]
		public string address2
		{
			get
			{
				return this._address2;
			}
			set
			{
				if ((this._address2 != value))
				{
					this.Onaddress2Changing(value);
					this.SendPropertyChanging();
					this._address2 = value;
					this.SendPropertyChanged("address2");
					this.Onaddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(3)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countryCode", DbType="NVarChar(3)")]
		public string countryCode
		{
			get
			{
				return this._countryCode;
			}
			set
			{
				if ((this._countryCode != value))
				{
					this.OncountryCodeChanging(value);
					this.SendPropertyChanging();
					this._countryCode = value;
					this.SendPropertyChanged("countryCode");
					this.OncountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalCode", DbType="NVarChar(12)")]
		public string postalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				if ((this._postalCode != value))
				{
					this.OnpostalCodeChanging(value);
					this.SendPropertyChanging();
					this._postalCode = value;
					this.SendPropertyChanged("postalCode");
					this.OnpostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdBy", DbType="NVarChar(200)")]
		public string createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				if ((this._createdBy != value))
				{
					this.OncreatedByChanging(value);
					this.SendPropertyChanging();
					this._createdBy = value;
					this.SendPropertyChanged("createdBy");
					this.OncreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(200)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this.OnupdatedByChanging(value);
					this.SendPropertyChanging();
					this._updatedBy = value;
					this.SendPropertyChanged("updatedBy");
					this.OnupdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this.OnupdatedDateChanging(value);
					this.SendPropertyChanging();
					this._updatedDate = value;
					this.SendPropertyChanged("updatedDate");
					this.OnupdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceId", DbType="NVarChar(200)")]
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				if ((this._sourceId != value))
				{
					this.OnsourceIdChanging(value);
					this.SendPropertyChanging();
					this._sourceId = value;
					this.SendPropertyChanged("sourceId");
					this.OnsourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceTypeId", DbType="BigInt")]
		public System.Nullable<long> sourceTypeId
		{
			get
			{
				return this._sourceTypeId;
			}
			set
			{
				if ((this._sourceTypeId != value))
				{
					this.OnsourceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._sourceTypeId = value;
					this.SendPropertyChanged("sourceTypeId");
					this.OnsourceTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="guest_guest_info", Storage="_guest", ThisKey="guestId", OtherKey="guestId", IsForeignKey=true)]
		internal guest guest
		{
			get
			{
				return this._guest.Entity;
			}
			set
			{
				if ((this._guest.Entity != value))
				{
					this.SendPropertyChanging();
					this._guest.Entity = value;
					this.SendPropertyChanged("guest");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.guest_xband")]
	public partial class guest_xband : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _guest_xband_id;
		
		private System.Nullable<long> _guestId;
		
		private System.Nullable<long> _xbandId;
		
		private string _createdBy;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private string _updatedBy;
		
		private System.Nullable<System.DateTime> _updatedDate;
		
		private string _sourceId;
		
		private System.Nullable<long> _sourceTypeId;
		
		private System.Nullable<bool> _active;
		
		private EntityRef<guest> _guest;
		
		private EntityRef<xband> _xband;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onguest_xband_idChanging(long value);
    partial void Onguest_xband_idChanged();
    partial void OnguestIdChanging(System.Nullable<long> value);
    partial void OnguestIdChanged();
    partial void OnxbandIdChanging(System.Nullable<long> value);
    partial void OnxbandIdChanged();
    partial void OncreatedByChanging(string value);
    partial void OncreatedByChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnupdatedByChanging(string value);
    partial void OnupdatedByChanged();
    partial void OnupdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedDateChanged();
    partial void OnsourceIdChanging(string value);
    partial void OnsourceIdChanged();
    partial void OnsourceTypeIdChanging(System.Nullable<long> value);
    partial void OnsourceTypeIdChanged();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    #endregion
		
		public guest_xband()
		{
			this._guest = default(EntityRef<guest>);
			this._xband = default(EntityRef<xband>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_xband_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long guest_xband_id
		{
			get
			{
				return this._guest_xband_id;
			}
			set
			{
				if ((this._guest_xband_id != value))
				{
					this.Onguest_xband_idChanging(value);
					this.SendPropertyChanging();
					this._guest_xband_id = value;
					this.SendPropertyChanged("guest_xband_id");
					this.Onguest_xband_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guestId", DbType="BigInt")]
		public System.Nullable<long> guestId
		{
			get
			{
				return this._guestId;
			}
			set
			{
				if ((this._guestId != value))
				{
					if (this._guest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnguestIdChanging(value);
					this.SendPropertyChanging();
					this._guestId = value;
					this.SendPropertyChanged("guestId");
					this.OnguestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xbandId", DbType="BigInt")]
		public System.Nullable<long> xbandId
		{
			get
			{
				return this._xbandId;
			}
			set
			{
				if ((this._xbandId != value))
				{
					if (this._xband.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnxbandIdChanging(value);
					this.SendPropertyChanging();
					this._xbandId = value;
					this.SendPropertyChanged("xbandId");
					this.OnxbandIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdBy", DbType="NVarChar(200)")]
		public string createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				if ((this._createdBy != value))
				{
					this.OncreatedByChanging(value);
					this.SendPropertyChanging();
					this._createdBy = value;
					this.SendPropertyChanged("createdBy");
					this.OncreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(200)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this.OnupdatedByChanging(value);
					this.SendPropertyChanging();
					this._updatedBy = value;
					this.SendPropertyChanged("updatedBy");
					this.OnupdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this.OnupdatedDateChanging(value);
					this.SendPropertyChanging();
					this._updatedDate = value;
					this.SendPropertyChanged("updatedDate");
					this.OnupdatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceId", DbType="NVarChar(200)")]
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				if ((this._sourceId != value))
				{
					this.OnsourceIdChanging(value);
					this.SendPropertyChanging();
					this._sourceId = value;
					this.SendPropertyChanged("sourceId");
					this.OnsourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceTypeId", DbType="BigInt")]
		public System.Nullable<long> sourceTypeId
		{
			get
			{
				return this._sourceTypeId;
			}
			set
			{
				if ((this._sourceTypeId != value))
				{
					this.OnsourceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._sourceTypeId = value;
					this.SendPropertyChanged("sourceTypeId");
					this.OnsourceTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="guest_guest_xband", Storage="_guest", ThisKey="guestId", OtherKey="guestId", IsForeignKey=true)]
		public guest guest
		{
			get
			{
				return this._guest.Entity;
			}
			set
			{
				if ((this._guest.Entity != value))
				{
					this.SendPropertyChanging();
					this._guest.Entity = value;
					this.SendPropertyChanged("guest");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="xband_guest_xband", Storage="_xband", ThisKey="xbandId", OtherKey="xbandId", IsForeignKey=true)]
		internal xband xband
		{
			get
			{
				return this._xband.Entity;
			}
			set
			{
				if ((this._xband.Entity != value))
				{
					this.SendPropertyChanging();
					this._xband.Entity = value;
					this.SendPropertyChanged("xband");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.source_type")]
	public partial class source_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _sourceTypeId;
		
		private string _sourceTypeName;
		
		private string _createdBy;
		
		private System.Nullable<System.DateTime> _createdDate;
		
		private string _updatedBy;
		
		private System.Nullable<System.DateTime> _updatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsourceTypeIdChanging(long value);
    partial void OnsourceTypeIdChanged();
    partial void OnsourceTypeNameChanging(string value);
    partial void OnsourceTypeNameChanged();
    partial void OncreatedByChanging(string value);
    partial void OncreatedByChanged();
    partial void OncreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedDateChanged();
    partial void OnupdatedByChanging(string value);
    partial void OnupdatedByChanged();
    partial void OnupdatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedDateChanged();
    #endregion
		
		public source_type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceTypeId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long sourceTypeId
		{
			get
			{
				return this._sourceTypeId;
			}
			set
			{
				if ((this._sourceTypeId != value))
				{
					this.OnsourceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._sourceTypeId = value;
					this.SendPropertyChanged("sourceTypeId");
					this.OnsourceTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceTypeName", DbType="NVarChar(200)")]
		public string sourceTypeName
		{
			get
			{
				return this._sourceTypeName;
			}
			set
			{
				if ((this._sourceTypeName != value))
				{
					this.OnsourceTypeNameChanging(value);
					this.SendPropertyChanging();
					this._sourceTypeName = value;
					this.SendPropertyChanged("sourceTypeName");
					this.OnsourceTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdBy", DbType="NVarChar(200)")]
		public string createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				if ((this._createdBy != value))
				{
					this.OncreatedByChanging(value);
					this.SendPropertyChanging();
					this._createdBy = value;
					this.SendPropertyChanged("createdBy");
					this.OncreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if ((this._createdDate != value))
				{
					this.OncreatedDateChanging(value);
					this.SendPropertyChanging();
					this._createdDate = value;
					this.SendPropertyChanged("createdDate");
					this.OncreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="NVarChar(200)")]
		public string updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this.OnupdatedByChanging(value);
					this.SendPropertyChanging();
					this._updatedBy = value;
					this.SendPropertyChanged("updatedBy");
					this.OnupdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedDate
		{
			get
			{
				return this._updatedDate;
			}
			set
			{
				if ((this._updatedDate != value))
				{
					this.OnupdatedDateChanging(value);
					this.SendPropertyChanging();
					this._updatedDate = value;
					this.SendPropertyChanged("updatedDate");
					this.OnupdatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
