//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.26 at 12:57:31 PM PDT 
//

package com.disney.xband.jms.lib.entity.gff;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facilityId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xBandId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="timeStampGMT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="tableId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="tableName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="changedDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="changedDetail" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="oldValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="newValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderNumbers" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "tableevent")
public class TableEvent {

    private BigInteger eventTypeId;
    private String event;
    private String facilityId;


    private String facilityOneSourceId;
    private String locationId;
    private String xBandId;
    private String source;
    private String terminal;
    private String timeStamp;
    private String timeStampGMT;
    private BigInteger tableId;
    private String tableName;
    //private ChangedDetails changedDetails;
    private String user;
    private List<OrderNumbers> orderNumbers;

    public TableEvent() {}

    @XmlElement(name = "eventtypeid")
    public BigInteger getEventTypeId() {
        return eventTypeId;
    }


    public void setEventTypeId(BigInteger value) {
        this.eventTypeId = value;
    }


    @XmlElement(name = "event")
    public String getEvent() {
        return event;
    }


    public void setEvent(String value) {
        this.event = value;
    }


    @XmlElement(name = "facilityid")
    public String getFacilityId() {
        if(facilityId == null) {
            return facilityOneSourceId;
        }
        return facilityId;
    }


    public void setFacilityId(String value) {
        this.facilityId = value;
    }

    @XmlElement(name = "facilityonesourceid")
    public String getFacilityOneSourceId() {
        return facilityOneSourceId;
    }

    public void setFacilityOneSourceId(String facilityOneSourceId) {
        this.facilityOneSourceId = facilityOneSourceId;
    }

    @XmlElement(name = "locationid")
    public String getLocationId() {
        return locationId;
    }


    public void setLocationId(String value) {
        this.locationId = value;
    }

    @XmlElement(name = "xbandid")
    public String getXBandId() {
        return xBandId;
    }


    public void setXBandId(String value) {
        this.xBandId = value;
    }


    @XmlElement(name = "source")
    public String getSource() {
        return source;
    }


    public void setSource(String value) {
        this.source = value;
    }


    @XmlElement(name = "terminal")
    public String getTerminal() {
        return terminal;
    }


    public void setTerminal(String value) {
        this.terminal = value;
    }


    @XmlElement(name = "timestamp")
    public String getTimeStamp() {
        return timeStamp;
    }


    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }


    @XmlElement(name = "timestampgmt")
    public String getTimeStampGMT() {
        return timeStampGMT;
    }


    public void setTimeStampGMT(String value) {
        this.timeStampGMT = value;
    }


    @XmlElement(name = "tableid")
    public BigInteger getTableId() {
        return tableId;
    }


    public void setTableId(BigInteger value) {
        this.tableId = value;
    }


    @XmlElement(name = "tablename")
    public String getTableName() {
        return tableName;
    }


    public void setTableName(String value) {
        this.tableName = value;
    }

    /*
    @XmlElement(name = "changeddetails")
    public TableEvent.ChangedDetails getChangedDetails() {
        return changedDetails;
    }


    public void setChangedDetails(ChangedDetails value) {
        this.changedDetails = value;
    }*/


    @XmlElement(name = "user")
    public String getUser() {
        return user;
    }


    public void setUser(String value) {
        this.user = value;
    }


    @XmlElement(name = "ordernumbers")
    public List<TableEvent.OrderNumbers> getOrderNumbers() {
        if (orderNumbers == null) {
            orderNumbers = new ArrayList<TableEvent.OrderNumbers>();
        }
        return this.orderNumbers;
    }

    public void setOrderNumbers(List<OrderNumbers> orderNumbersList) {

    }


    /**
     * <p>Java class for anonymous compuex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="changedDetail" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="fieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="oldValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="newValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
    public static class ChangedDetails {

        private List<ChangedDetail> changedDetail;


        @XmlElement(name = "changeddetail")
        public List<TableEvent.ChangedDetails.ChangedDetail> getChangedDetail() {
            if (changedDetail == null) {
                changedDetail = new ArrayList<TableEvent.ChangedDetails.ChangedDetail>();
            }
            return this.changedDetail;
        }

        public static class ChangedDetail {

            public ChangedDetail() {}

            @XmlElement(name = "fieldName")
            private String fieldName;
            @XmlElement(name = "oldValue")
            private String oldValue;
            @XmlElement(name = "newValue")
            private String newValue;

            @XmlElement(name = "fieldname")
            public String getFieldName() {
                return fieldName;
            }


            public void setFieldName(String value) {
                this.fieldName = value;
            }

            @XmlElement(name = "oldvalue")
            public String getOldValue() {
                return oldValue;
            }


            public void setOldValue(String value) {
                this.oldValue = value;
            }

            @XmlElement(name = "newvalue")
            public String getNewValue() {
                return newValue;
            }

            public void setNewValue(String value) {
                this.newValue = value;
            }

        }

    }
    */

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    public static class OrderNumbers {

        public OrderNumbers() {}
        private String orderNumber;


        @XmlElement(name = "ordernumber")
        public String getOrderNumber() {
            return orderNumber;
        }


        public void setOrderNumber(String value) {
            this.orderNumber = value;
        }

    }

}
